[package]
name = "linkdrop-wrapper"
version = "0.1.0"
authors = ["eclipseeer <eclipseeer@gmail.com>"]
edition = "2018"

[workspace]
members = ['linkdrop', 'user', 'near-campaign']

[dev-dependencies]
near-sdk = "4.0.0-pre.2"
near-sdk-sim = "4.0.0-pre.2"
near-crypto = "0.1.0"
linkdrop = { path = "linkdrop" }
user = { path = "user" }
near-campaign = { path = "near-campaign" }
