[package]
name = "nft_campaign"
version = "1.0.0"
authors = ["eclipseeer <eclipseeer@gmail.com>"]
edition = "2018"

[dependencies]
near-sdk = "4.0.0-pre.6"
common = { path = "../../../common" }

[lib]
crate-type = ["cdylib", "rlib"]
